call C:\Python27\Lib\site-packages\PyQt4\pyuic4 -o ..\main_window_ui.py main_window.ui
call C:\Python27\Lib\site-packages\PyQt4\pyuic4 -o ..\resource_ui.py resource.ui
call C:\Python27\Lib\site-packages\PyQt4\pyuic4 -o ..\scenario_ui.py scenario.ui
call C:\Python27\Lib\site-packages\PyQt4\pyuic4 -o ..\project_ui.py project.ui
call C:\Python27\Lib\site-packages\PyQt4\pyuic4 -o ..\new_project_ui.py new_project.ui
call C:\Python27\Lib\site-packages\PyQt4\pyuic4 -o ..\new_scenario_ui.py new_scenario.ui
call C:\Python27\Lib\site-packages\PyQt4\pyuic4 -o ..\progress_ui.py progress.ui
call C:\Python27\Lib\site-packages\PyQt4\pyuic4 -o ..\welcome_ui.py welcome.ui
call C:\Python27\Lib\site-packages\PyQt4\pyuic4 -o ..\settings_ui.py settings.ui
call C:\Python27\Lib\site-packages\PyQt4\pyrcc4 -o ..\gui_rc.py gui.qrc